export const EPS = 0.0001;
export const customCollisionRadiusOptsType = Symbol('collision-radius-options');
export const customCollisionExtentsOptsType = Symbol('collision-extents-options');
export const customPhysxCapsuleOptsType = Symbol('physx-capsule-options');
export const customPhysxMeshOptsType = Symbol('physx-mesh-options');
export const customOpaqueColorType = Symbol('opaque-color');
export const NATIVE_COMPONENTS = ['animation', 'collision', 'input', 'light', 'mesh', 'physx', 'text', 'view'];
export const EDITOR_BUNDLE_DEFAULT = 'cache/js/_editor_bundle.cjs';
export const EDITOR_BUNDLE_EXTRA_DEFAULT = 'editor-bundle-extra.js';